// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSySTbU5nkNgISre_qC3murPNbGM25qVU',
    appId: '1:742306578090:web:29f56d30ddf27cadb29ad3',
    messagingSenderId: '742306578090',
    projectId: 'booking-restaurant-8a5f7',
    authDomain: 'booking-restaurant-8a5f7.firebaseapp.com',
    storageBucket: 'booking-restaurant-8a5f7.firebasestorage.app',
    measurementId: 'G-Y4V5VSN7XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kwCAHNAkkv68Z1BqL6mcwkbCGfRW7CA',
    appId: '1:742306578090:android:1fe14926c7a61a9ab29ad3',
    messagingSenderId: '742306578090',
    projectId: 'booking-restaurant-8a5f7',
    storageBucket: 'booking-restaurant-8a5f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIawG5V879jwGuDz3o1srZXNPd-ZcpG3s',
    appId: '1:742306578090:ios:884df38e318e223fb29ad3',
    messagingSenderId: '742306578090',
    projectId: 'booking-restaurant-8a5f7',
    storageBucket: 'booking-restaurant-8a5f7.firebasestorage.app',
    iosBundleId: 'com.example.bookingRestaurant',
  );
}
